version: "3.8"

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: quocdanh
      MYSQL_DATABASE: project
      MYSQL_USER: danh
      MYSQL_PASSWORD: danh
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"

  app:
    build: .
    environment:
      FLASK_APP: app.py
      FLASK_ENV: development
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: quocdanh
      MYSQL_DB: project
    ports:
      - "5000:5000"
    depends_on:
      - db
